# Generated by Django 3.0.1 on 2024-02-09 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sajda_feed_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hadithcard',
            name='hadith_book',
            field=models.TextField(max_length=100),
        ),
    ]
