# Generated by Django 3.0.1 on 2024-02-09 18:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sajda_feed_app', '0002_auto_20240209_1109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hadithcard',
            name='hadith_book',
        ),
        migrations.RemoveField(
            model_name='hadithcard',
            name='hadith_number',
        ),
        migrations.RemoveField(
            model_name='qurancard',
            name='surah_number',
        ),
        migrations.AddField(
            model_name='hadithcard',
            name='hadith_text',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='qurancard',
            name='arabic_text',
            field=models.TextField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
