# Generated by Django 3.0.1 on 2024-02-14 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sajda_feed_app', '0007_customuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picturecard',
            name='image',
            field=models.ImageField(upload_to='static/inspiring_pictures/'),
        ),
    ]
