# Generated by Django 3.0.1 on 2024-02-14 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sajda_feed_app', '0008_auto_20240214_0759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picturecard',
            name='image',
            field=models.ImageField(upload_to='inspiring_pictures/'),
        ),
    ]
