# Generated by Django 3.0.1 on 2024-02-14 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sajda_feed_app', '0009_auto_20240214_0811'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtubecard',
            name='youtube_url',
            field=models.TextField(default='https://youtube.com/', max_length=100),
            preserve_default=False,
        ),
    ]
