# Generated by Django 3.0.1 on 2024-02-14 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sajda_feed_app', '0010_youtubecard_youtube_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='youtubecard',
            old_name='youtube_url',
            new_name='video_id',
        ),
    ]
