# Generated by Django 3.2.24 on 2024-02-14 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sajda_feed_app', '0011_auto_20240214_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picturecard',
            name='image',
            field=models.ImageField(default='media/placeholders/image-card-placeholder.jpg', upload_to='inspiring_pictures/'),
        ),
        migrations.AlterField(
            model_name='youtubecard',
            name='preview_image',
            field=models.ImageField(default='media/placeholders/youtube-card-placeholder.jpg', upload_to='youtube_videos/'),
        ),
        migrations.AddConstraint(
            model_name='dhikrcard',
            constraint=models.CheckConstraint(check=models.Q(('user_progress__gte', 0), ('user_progress__lt', 100)), name='user_progress is between 1 and 100'),
        ),
    ]
